// TODO: verify every name, address and description before submitting.
export const places = [
  { name: "National Heroes Acre", address: "Harare-Bulawayo Road, west of Harare CBD", description: "A national monument honoring figures from Zimbabwe's liberation history, with a statue group set on a hillside overlooking the city.", image: "images/heroes-acre.webp", alt: "Golden statue group at National Heroes Acre with the Zimbabwean flag" },
  { name: "St Mary's Cathedral", address: "Central Harare", description: "A stone cathedral with twin towers and a large crucifix at its entrance, a well-known landmark in the city.", image: "images/st-marys-cathedral.webp", alt: "Twin-towered stone cathedral with a crucifix in the foreground" },
  { name: "Eastgate Centre", address: "Corner Robert Mugabe Road and Second Street, Harare CBD", description: "A well-known office and shopping complex whose passive cooling design was inspired by termite mounds.", image: "images/eastgate.webp", alt: "Eastgate Centre lit up at dusk with light trails from passing traffic" },
  { name: "Jacaranda Streets", address: "Streets across central Harare", description: "Each spring, jacaranda trees line many Harare streets with purple blossom, one of the city's best-loved sights.", image: "images/jacaranda-street.webp", alt: "Harare street lined with purple jacaranda trees in bloom, seen from above" },
  { name: "Harare International Airport", address: "Airport Road, southeast of Harare", description: "The main gateway for air travel into Zimbabwe, connecting Harare to regional and international destinations.", image: "images/airport.webp", alt: "Airport control tower rising above the terminal and lawn" },
  { name: "Harare CBD Tower", address: "Central Harare", description: "A modern glass office tower in the central business district, with a pedestrian bridge linking nearby buildings.", image: "images/bank-tower.webp", alt: "Tall glass office tower beside a pedestrian bridge in central Harare" },
  { name: "Harare City Centre", address: "Central Business District, Harare", description: "High-rise offices, hotels and shops sit among tree-lined streets in the commercial heart of the city.", image: "images/city-centre.webp", alt: "Harare city centre buildings above tree tops on a clear morning" },
  { name: "Harare Skyline", address: "Central Harare", description: "Harare's skyline of modern towers is set among parks and jacaranda-lined avenues.", image: "images/harare-skyline.webp", alt: "Harare skyline with towers, a park and jacaranda trees" }
];
